spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://115.159.103.42:3306/spicybar?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: spicybar
    password: spicybar
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration